services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-app
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    ports:
      - "5000:5000"
    networks:
      - url-net
  
  cassandra:
    image: cassandra:4.1
    container_name: url-db
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    networks:
      - url-net
  
  redis:
    image: redis:7
    container_name: url-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - url-net

volumes:
  cassandra_data:
    name: url-db
  redis_data:
    name: url-redis

networks:
  url-net:
    name: url-net
    driver: bridge